### ISSUE TITLE
use of unstable library feature 'renamed_spin_loop'

### ISSUE THREAD

**Issue by HBnetDE** [rust-osdev/uart_16550#17]
I have tried to add this crate to an empty project with rust nightly.
When trying to build compilation fails with error:
`error[E0658]: use of unstable library feature 'renamed_spin_loop'`
It also recommends to add the crate attribute `#![feature(renamed_spin_loop)]`
However, adding this to my crate does nothing.

I have then tried to clone this crate and build it directly.
This causes the same error.
However compilation is successfull after adding the crate attribute to the top of uart_16550's lib.rs.

Is this an error on my end?

**Comment by phil-opp** [comment]
What is the output of `rustc --version` for you?

**Comment by HBnetDE** [comment]
It was `rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)` when I wrote this.
I then updated to `rustc 1.54.0-nightly (4e3e6db01 2021-05-18)`  and it builds now.

Thank you.

**Comment by phil-opp** [comment]
Great to hear that!
