### ISSUE TITLE
Remove `nightly`/`stable` features when Rust 1.61 is released

### ISSUE THREAD

**Issue by phil-opp** [rust-osdev/uart_16550#23]
The `const_ptr_offset` feature was stabilized in https://github.com/rust-lang/rust/pull/93957. We removed that feature gate from this crate in https://github.com/rust-osdev/uart_16550/pull/22. Right now, we still need the `stable` and `nightly` features of this crate to make `MmioSerialPort::new` a const function on nightly, but on Rust 1.61 this should be supported on stable as well. So we should remove the crate features when 1.61 is released.

**Comment by Hugo4IT** [comment]
is there a temporary workaround for this, because right now I can't compile my stuff because of this.

**Comment by phil-opp** [comment]
@Hugo4IT This issue is just about removing some features of this crate in the future, it should not be releated to any breakage.

There was a recent breakage on the latest nightly that was fixed by #22. You can update to that fix by running `cargo update -p uart_16550`. If that doesn't fix your problem, please open a new issue with your exact compile error, and the `rustc` and `uart_16550` versions that you're using.

**Comment by Hugo4IT** [comment]
I see, I thought running `cargo clean` before running again would update everything (my dependency is `uart_16550 = "0.2"`). Thanks for your quick help, it works now.
