### ISSUE TITLE
Just a question. Why sending 8, space, 8 for a backspace or a delete ascii ctrl char ?

### ISSUE THREAD

**Issue by maduma** [rust-osdev/uart_16550#26]
https://github.com/rust-osdev/uart_16550/blob/d401ea103641cc06182c404840a5ba2896eebe72/src/mmio.rs#L83

**Comment by Kage-Yami** [comment]
> https://github.com/rust-osdev/uart_16550/blob/d401ea103641cc06182c404840a5ba2896eebe72/src/mmio.rs#L83

I think [this comment](https://github.com/rust-osdev/uart_16550/issues/19#issuecomment-988174471) would answer that question.

**Comment by maduma** [comment]
Thanks !
