### ISSUE TITLE
might want to update the x86_64 dep

### ISSUE THREAD

**Issue by haraldh** [rust-osdev/uart_16550#3]
https://github.com/rust-osdev/uart_16550/blob/520b9d65926cd88a3d41e793575c65c23767442b/Cargo.toml#L12

**Comment by phil-opp** [comment]
Sure! I'd be happy to merge a pull request for this.

**Comment by haraldh** [comment]
Btw, there is [dependabot](https://github.com/marketplace/dependabot-preview) automatically filing PRs for dep updates, which would trigger the CI :)

**Comment by phil-opp** [comment]
My problem with depandabot is that it will file a PR for every single patch version, which is not necessary with cargo and semantic versioning.
